# fly.toml app configuration file generated for elemental on 2025-05-05T15:36:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elemental'
primary_region = 'fra'

[build]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
